### PR TITLE
Fix indentation of settings file

### PR DESCRIPTION
**Pull request by eppsilon**

### CODE REVIEW

**Comment by 50Wliu** [comment]
Ouch.

@benogle Are these still needed now that we have `autocomplete-sass`?

**Comment by benogle** [comment]
> Are these still needed now that we have autocomplete-sass?

Yeah they are. autocomplete only completes properties and their values.

**Comment by benogle** [comment]
This seems legit. I say :ship:

**Comment by 50Wliu** [comment]
Thanks @eppsilon!

**Pull request merged**
