### PR TITLE
Recognize solitary @mix and @namespace as @-rule

### LINKED ISSUE #138: Immediate highlighting for @mixin and @namesapce
Right now, `@mixin` isn't highlighted until the first letter of the name of the mixin is typed:

104db036-c155-4d35-989c-51fadf3cdc15

Ideally, `@mixin` (and `@namespace`) should be highlighted as soon as you type in the letter `n` to give the author an immediate feedback, like `@include`, `@import`, and some others:

e1cd7d66-1f3f-47e2-a5a6-0b8d0875f9bf

### PR DESCRIPTION
**Pull request by esdoppio**
closes #138

### CODE REVIEW

**Comment by 50Wliu** [comment]
Comments in #137 apply here as well.

**Comment by esdoppio** [comment]
@50Wliu Anything else?

May I ask what "flavor" of the regex is using? JavaScript?

**Comment by 50Wliu** [comment]
More comments over at #137.  Language regexes use the Oniguruma engine which as far as I understand is extremely similar to PHP's.

**Comment by esdoppio** [comment]
@50Wliu Thanks! For all your help and guidance.

Just checked, it's also integrated into Ruby.

**Pull request merged**
