### PR TITLE
fix: `@each` block end

### LINKED ISSUE #267: Syntax highlighting of @each directive inside .vue style block
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Using `@each` SCSS directive inside a .vue file breaks subsequent syntax highlighting. Digging through `grammars/scss.cson` it seems like `'end': '\\s*((?=}))'` is incorrect.

Replacing the line with `'end': '\\s*(?={)'` as in the similar `@if`-directive fixes the issue.

See the following branch in our fork for a fix that solves the issue https://github.com/internetfriendsforever/language-sass/tree/each-directive-fix 

Commit is here https://github.com/internetfriendsforever/language-sass/commit/8e56bc8f00be3248604b53a2749dcf09029ec1f3

### Steps to Reproduce

1. use `@each` directive in 
```
<style lang="scss">
@each $key, $value in $map {
    .color-#{$key} {
      stroke: $value;
    }
 }
</style>
``` 

**Expected behavior:**

Normal syntax highlighting

**Actual behavior:**

Syntax highlighting after `@each` directive is broken. Affects both SCSS within the `<style>` block and the remaining code in the document. 

**Reproduces how often:**

100% of the time for `<style lang="scss">` blocks inside a `.vue` file 
0% of the time in a pure `.scss` file.

### Versions

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.10
git 2.20.1
```

Running Mac OS 10.14.6

### PR DESCRIPTION
**Pull request by jquense**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Fixes, syntax highlighting for `@each` statements. Updated to match the other control flow/iteration patterns (see `if`, `else`, `for`, etc)

old:
image

new: 
image

### Benefits

Code will be highlighted more accurately. Specifically in nested language cases, such as CSS-in-js style colocation of scss styles in js

### Possible Drawbacks

It could be the wrong fix?

### Applicable Issues

Fixes #267

### CODE REVIEW

**Comment by rsese** [comment]
Awesome thank you @jquense :+1:  Would you be able to add a test so that future changes don't break your fix?

**Comment by jquense** [comment]
Sure I can try, do they have to be in coffee script? I've never used that but probably can pick it ip

**Comment by rsese** [comment]
:bow:

> do they have to be in coffee script? 

Sorry, yes looks like the [current specs are CoffeeScript](https://github.com/atom/language-sass/blob/566238ee7a9321722f7fc4fb0bd04ba08ba7b187/spec/scss-spec.coffee).

**Comment by jquense** [comment]
getting coffeescript to work here is a real barrier to contribution fyi...

**Pull request closed without merging**
