### PR TITLE
Add some missing properties and values

### PR DESCRIPTION
**Pull request by silvenon**
* Flexbox properties and values

  * properties: `flex-flow` `flex-basis` `flex-grow` `flex-wrap` `flex-shrink` `flex-direction` `align-items` `align-content` `align-self` `justify-content` `order` `inline-flex`
  * values: `column` `column-reverse` `flex-end` `flex-start` `flex` `row` `row-reverse` `space-around` `space-between` `stretch` `wrap` `wrap-reverse`
  * [reference](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

* missing `vmax` unit

* other properties and values

  * properties: `animation-fill-mode` `object-fit` `object-position` `backface-visibility`
  * values: `currentColor` `fill` `contain` `cover` `table` `table-cell` `table-column` `table-column-group` `table-row` `table-row-group` `inline-flex`

### CODE REVIEW

**Comment by silvenon** [comment]
Unfortunately, the value `table` and properties `object-fit` and `object-position` won't highlight well because `table` and `object` are HTML elements that get matched first. I'll see if I can fix that (in another PR).

**Comment by silvenon** [comment]
Maybe it's best to pull this soon, because any other commits or PRs dealing with these lines will cause conflicts :smiley:

**Comment by kevinsawicki** [comment]
Thanks for adding these, apologies for the delay in merging it :ship:

**Comment by silvenon** [comment]
Great!

**Pull request merged**
