### PR TITLE
Recognize -webkit-*, -moz-*, and -ms-* as property names

### PR DESCRIPTION
**Pull request by esdoppio**

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can you add a spec for this please?  And does SCSS already do this?

**Comment by esdoppio** [comment]
Sure.

Yep, SCSS already does this, slightly different:

```
-webkit-[A-Za-z-]+|-moz-[A-Za-z-]+|-o-[A-Za-z-]+|-ms-[A-Za-z-]+|-khtml-[A-Za-z-]+
```

* It's effectively the same as `-(webkit|moz|o|ms|khtml)-[…]+`, much longer, but not necessarily easier to understand.
* I didn't add `-khtml-` in `sass.cson`, coz no one actually uses it in stylesheets now.
* Not sure why the author chose to match `A-Z`; I don't know any properties whose name contains              capitalized letters.

Correct me if I'm wrong :metal: 

Opera had stopped using `-o-` a couple of years ago; the newer versions use `-webkit-` instead. Should we keep `-o-`?

**Comment by 50Wliu** [comment]
> Should we keep -o-?

Let's drop it.

**Comment by esdoppio** [comment]
@50Wliu Anything else?

**Comment by esdoppio** [comment]
@50Wliu Anything else?

**Pull request merged**
