### PR TITLE
Add Sass auto-indentation rules

### LINKED ISSUE #95: Auto indent isn't working
When working with SASS files and pressing enter, the auto indent feature isn't working. Tested on a clean install, no plugins or modifications.

### PR DESCRIPTION
**Pull request by 50Wliu**
Basically, auto-indent if:
* the line does not contain a colon
OR
* the line is a pseudo-class/element
OR
* the line is an at-rule

This is my first time writing auto-indentation regexes.  Things might not work as expected.

Fixes #95

/cc @johnburkhard, @serhiicss

### CODE REVIEW

**Comment by 50Wliu** [comment]
Please note that no deindent rules are included, as there is no way of knowing when to.

**Comment by controversial** [comment]
What does this mean? If this is auto-indentation for `.sass` files, I can't wait to see this in Atom. When can I expect to see this in Atom?

**Comment by 50Wliu** [comment]
@controversial it should be in Atom 1.10.0-beta3 already.

**Comment by controversial** [comment]
Awesome!

**Pull request merged**
