### PR TITLE
Recognize object-* as property name

### LINKED ISSUE #126: `object-position` and `object-fit` properties don't highlight correctly
language-css gets it right:
css-object-properties
but language-sass doesn't:
scss-object-propertes

### PR DESCRIPTION
**Pull request by esdoppio**
closes #126

### CODE REVIEW

**Comment by esdoppio** [comment]
Question: Why does
https://github.com/atom/language-sass/blob/master/grammars/sass.cson#L294
have 2 more property names: `-webkit-border-radius`, `-webkit-box-shadow` than
https://github.com/atom/language-sass/blob/master/grammars/sass.cson#L285 ?

**Comment by 50Wliu** [comment]
The two probably just got out of sync by accident and no one noticed.  If you want feel free to add the missing ones.

**Comment by esdoppio** [comment]
But there're still so many experimental/prefixed properties (`-moz-border-radius` and stuff) missing in the list. Shouldn we abstract the prefixes out?

**Comment by 50Wliu** [comment]
Yes, that would probably be a good idea.

**Pull request merged**
