### PR TITLE
New Snippets for Sass Module, Fix to Increase Indent Pattern

### PR DESCRIPTION
**Pull request by sarsamurmu**
### Description of the Change
This adds New Snippets for Sass Module. This also adds increase Indent for round bracket.

### Benefits
Same as Description of Change

### Possible Drawbacks
There are no drawbacks.

### Applicable Issues
None

### CODE REVIEW

**Comment by rsese** [comment]
Thanks for the contribution!  For reference, it looks like https://github.com/atom/language-sass/pull/269 was opened to add this functionality as well (in addition to other new syntax it looks like).  Related to the drawback you mentioned:

 > It doesn't include support of Sass, only in SCSS.

It also looks like it provides support for Sass as well.

Would you be in favor of closing this pull request in favor of #269 since it seems to provide support for more of the new syntax, has support for Sass, and has tests?

**Comment by sarsamurmu** [comment]
Yes, you can close this Pull Request.

**Comment by sarsamurmu** [comment]
@rsese Hey, I removed the change with `scss.cson` and Just left the snippets and increase indent pattern. I hope you can merge it now :)

**Comment by rsese** [comment]
Thanks @sarsamurmu - we generally don't accept modifications for snippets in the language packages since they are easily overridden and we expect that people will do so for their own purposes. People can find instructions on how to create their own snippets in the [Flight Manual](https://flight-manual.atom.io/using-atom/sections/snippets/). Viewing a language package that provides snippets also allows people to copy the current version as a starting place for creating their own.

Thanks for the suggestion but we're going to leave things as they are for now unless the current snippet produces invalid code.

**Pull request closed without merging**
